[package]

name = "combine"
version = "2.5.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Fast parser combinators on arbitrary streams with zero-copy support."

repository = "https://github.com/Marwes/combine"
documentation = "https://docs.rs/combine"

readme = "README.md"

keywords = ["parser", "parsing", "combinators", "ll"]

categories = ["parsing"]

license = "MIT"

[lib]
name = "combine"
path = "src/lib.rs"

[dependencies]
ascii = "0.7.0"
byteorder = "1.1.0"
regex = { version = "0.2.0", optional = true }

[dev-dependencies]
bencher = "0.1.3"
lazy_static = "0.2.8"

[features]
# Run the mp4 benchmark, requires a mp4 file named `small.mp4` in the benches directory
mp4 = []
doc = ["regex"]

[[bench]]
name = "json"
harness = false

[[bench]]
name = "http"
harness = false

[[bench]]
name = "mp4"
harness = false
required-features = ["mp4"]

[package.metadata.docs.rs]
features = ["doc"]
