[package]

name = "combine"
version = "3.3.4-alpha.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Fast parser combinators on arbitrary streams with zero-copy support."

repository = "https://github.com/Marwes/combine"
documentation = "https://docs.rs/combine"

readme = "README.md"

keywords = ["parser", "parsing", "combinators", "ll"]

categories = ["parsing", "no-std"]

license = "MIT"

[lib]
name = "combine"
path = "src/lib.rs"

[dependencies]
ascii = "0.7.0"
byteorder = "1.1.0"
either = "1"
unreachable = "1.0.0"
regex = { version = "0.2.0", optional = true }
memchr = { version = "2", default-features = false }

[dev-dependencies]
bencher = "0.1.3"
lazy_static = "1.0"

futures = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
bytes = "0.4"
quickcheck = "0.6"
quick-error = "1.0"

[features]
default = ["std"]
# Run the mp4 benchmark, requires a mp4 file named `small.mp4` in the benches directory
mp4 = []
doc = ["regex"]
std = ["memchr/use_std"]

[[bench]]
name = "json"
harness = false

[[bench]]
name = "http"
harness = false

[[bench]]
name = "mp4"
harness = false
required-features = ["mp4"]

[[example]]
name = "async"
required-features = ["std"]

[[example]]
name = "date"

[[example]]
name = "number"

[[example]]
name = "readme"

[[example]]
name = "ini"

[package.metadata.docs.rs]
features = ["doc"]

[profile.bench]
lto = true
codegen-units = 1
