[package]

name = "combine"
version = "4.0.0-alpha.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Fast parser combinators on arbitrary streams with zero-copy support."

repository = "https://github.com/Marwes/combine"
documentation = "https://docs.rs/combine"

readme = "README.md"

keywords = ["parser", "parsing", "combinators", "ll"]

categories = ["parsing", "no-std"]

license = "MIT"

edition = "2018"

[lib]
name = "combine"
path = "src/lib.rs"

[dependencies]
ascii = { version = "0.9.1", default-features = false }
byteorder = { version = "1.1.0", default-features = false }
either = { version = "1", default-features = false }
unreachable = "1.0.0"
regex = { version = "1", optional = true }
memchr = { version = "2.2", default-features = false }

[dev-dependencies]
criterion = "0.2"
lazy_static = "1.0"

futures = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
bytes = "0.4"
quickcheck = "0.6"
quick-error = "1.0"

[features]
default = ["std"]
# Run the mp4 benchmark, requires a mp4 file named `small.mp4` in the benches directory
mp4 = []
doc = ["regex"]
std = ["memchr/use_std", "either/use_std", "byteorder/std", "ascii/std"]

[[bench]]
name = "json"
harness = false

[[bench]]
name = "http"
harness = false

[[bench]]
name = "mp4"
harness = false
required-features = ["mp4"]

[[example]]
name = "async"
required-features = ["std"]

[[example]]
name = "date"

[[example]]
name = "number"

[[example]]
name = "readme"

[[example]]
name = "ini"

[package.metadata.docs.rs]
features = ["doc"]

[profile.bench]
lto = true
codegen-units = 1
