[package]

name = "parser-combinators"
version = "0.2.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

description = "Parser combinators based on the Haskell library parsec"

repository = "https://github.com/Marwes/parser-combinators"
documentation = "http://marwes.github.io/parser-combinators/doc/parser-combinators/index.html"

keywords = ["parser"]

license = "MIT"

[lib]

name = "parser-combinators"
path = "src/lib.rs"
